CREATE TABLE Movie (
    TITLE VARCHAR2(100) PRIMARY KEY,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE  DATE DEFAULT SYSDATE,
    TIME VARCHAR2(10) NOT NULL,
    PRICE NUMBER NOT NULL,
    LIMIT NUMBER NOT NULL,
    DIRECT  VARCHAR2(20),
    ARTIST  VARCHAR2(100)
);

CREATE TABLE Reserve (
    R_ID VARCHAR2(10) NOT NULL,
    R_TITLE VARCHAR2(100),
    R_PRICE NUMBER NOT NULL,
    CONSTRAINTS PK_RESERVE PRIMARY KEY (R_ID, R_TITLE)
);

CREATE TABLE User_info (
    USER_ID VARCHAR2(10) PRIMARY KEY,
    USER_PW VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(10) NOT NULL,
    GENDER VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE_NUMBER VARCHAR2(12) NOT NULL,
    PURCHASE NUMBER,
    GRADE NUMBER,
    BIRTH_DATE DATE
);

CREATE TABLE Board_t (
    B_NUM NUMBER PRIMARY KEY,
    B_ID VARCHAR2(20) NOT NULL,
    B_TITLE VARCHAR2(100),
    B_CONTEXT LONG NOT NULL,
    B_DIRECT VARCHAR2(20),
    B_ARTIST VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINTS FK_TITLE FOREIGN KEY (B_TITLE) REFERENCES Movie (TITLE)
);

CREATE SEQUENCE board_seq;