-- 댓글 테이블
CREATE TABLE BOARD_COMMENT 
(
  COMMENT_NUM NUMBER NOT NULL,
  COMMENT_BOARD NUMBER NOT NULL,
  COMMENT_ID VARCHAR2(15),
  COMMENT_DATE DATE,
  COMMENT_PARENT NUMBER,
  COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
  CONSTRAINT PK_comment PRIMARY KEY(COMMENT_NUM),
  CONSTRAINT FK_comment FOREIGN KEY(COMMENT_BOARD) REFERENCES Board_t(B_NUM)
);
 
-- Board_t는 게시판 테이블을, B_NUM은 글번호를 나타낸다.

create sequence COMMENT_SEQ;
